version: 0.2

phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install

  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
      - npm run test
      # Remove all unit tests to reduce the size of the package that will be ultimately uploaded to Lambda
      - rm -rf ./__tests__
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --production

  build:
    commands:
      # Build the SAM application
      - sam build --use-container
      # Package the SAM application using the output template file
      - sam package --output-template-file packaged.yaml --s3-bucket $S3_BUCKET

  post_build:
    commands:
      # Deploy the SAM application
      - sam deploy --template-file packaged.yaml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM --parameter-overrides ParameterKey=Environment,ParameterValue=$ENVIRONMENT --no-fail-on-empty-changeset

artifacts:
  type: zip
  files:
    - packaged.yaml

cache:
  paths:
    - '/root/.npm/*'
