export const PARAMS = Object.freeze({
    EMAIL_LOGGING_TITLE_CALL_FARGATE: "Error from the Scrape Suno Song Lambda - {time}",
    EMAIL_LOGGING_TITLE_CHECK_FARGATE_TASK: "Error from Check Song Status Lambda - {time}",
    SUPABASE_JWT_LIFETIME: 60,
    SUPABASE_AWS_LAMBDA_ROLE: "aws_role",
    SUPABASE_SONG_GENERATIONS_TABLE: "discord_song_generations",
    SUPABASE_SCRAPER_STATUS_TABLE: "scraper_status",
    SUPABASE_SCHEMA: "backpack_bots",
    SUPABASE_SONG_BUCKET: "song-output-audio",
    MAX_SONG_PROMPT_LENGTH: 180,
    FARGATE_WARMUP: 100,
    MIN_RUNTIME: 420,
    MAX_RUNTIME: 840,
    MIN_SUNO_CREDIT_BALANCE: 50,
    EMAIL_FORMATTED_MESSAGE_CALL_FARGATE: "Hi, I encountered an error while starting a new Fargate task: {errorMessage}. The phone number for this call was {phoneNumber}. The generation ID for this call was {generationId}.",
    EMAIL_FORMATTED_MESSAGE_CHECK_FARGATE: "Hi, I encountered an error while checking a Fargate task: {errorMessage}. The generation ID for this call was {generationId}.",
    SONG_STATUS_ERROR: "song-status-error",
    SCRAPE_SONG_ERROR: "scrape-song-error",
    CREATE_SONG_VIDEO_ERROR: "create-song-video",
    OUTPUT_VIDEO_WIDTH: 1080,
    OUTPUT_VIDEO_HEIGHT: 1920,
    OUTPUT_CLIPPING_FOR_LYRICS: 0.9,
    MAX_FONT_SIZE: 50,
    OUTPUT_LYRICS_ROW_HEIGHT_DELTA: 65,
    OUTPUT_LYRICS_MIN_FONT_SIZE: 21,
    OUTPUT_LYRICS_FONT: "Lexend Deca",
    OUTPUT_LYRICS_TOTAL_PADDING: 600,
    OUTPUT_LYRICS_FILL_STYLE: "white",
    OUTPUT_LYRICS_TEXT_ALIGN: "center",
    OUTPUT_LYRICS_TEXT_BASELINE: "middle",
    OUTPUT_LYRICS_TOP_EXTRA_CLIP: 50,
    OUTPUT_LYRICS_FONT_FILE_NAME: "lexend-deca",
    MAX_SONG_DOWNLOAD_WAIT_TIME: 15
});